// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using GitWatchdog.Presentation.ViewModel;
using GitWatchdog.Presentation.Helpers;
using System.Reactive.Concurrency;
using Gitwatchdog.MacOS.TableViewSource;

namespace Gitwatchdog.MacOS
{
	public partial class GitwatchdogContainer : NSViewController
	{
        private MainViewModel ViewModel { set; get; }

        private GitwatchdogTableViewSource _tableViewSource;

		public GitwatchdogContainer (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Hopefully, the CurrentThread scheduler is the MacOS dispatcher.
            DispatcherHelper.DefaultDispatcherScheduler = Scheduler.CurrentThread;
            ViewModel = new MainViewModel();
        }

		public override void ViewDidAppear()
		{
			base.ViewDidAppear();

            _tableViewSource = new GitwatchdogTableViewSource(ViewModel.Items, GitWatchdogList);
		}

		public override void ViewDidDisappear()
		{
			base.ViewDidDisappear();

            _tableViewSource = null;
            GitWatchdogList.DataSource = null;
		}
	}
}
